### ISSUE TITLE
Reproducing Learned Augmentation (CycleGAN)

### ISSUE THREAD

**Issue by ysharma1126** [deepmind/distribution_shift_framework#4]
1. Was CycleGAN trained on the true, uncorrelated distribution, implying the same model was used for each dataset averaged over in Fig. 3? 
2. Any plans for release?

**Comment by oawiles** [comment]
1. No, CycleGAN was trained on the train set, so it inherited the biases of the training set. We trained a different model for each biased training set so a different model was used for each result (and seed).
2. At the moment we are not planning on this.
